# Generated by Django 2.2.5 on 2019-09-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FPP', '0002_auto_20190903_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
