# Generated by Django 2.2.6 on 2019-11-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPP', '0003_remove_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='debt',
            field=models.FloatField(default=0),
        ),
    ]
